//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinnohUndergroundRNGLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SinnohUndergroundRNGLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ARMOR_FOSSIL {
            get {
                object obj = ResourceManager.GetObject("ARMOR_FOSSIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BLUE_SHARD {
            get {
                object obj = ResourceManager.GetObject("BLUE_SHARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CLAW_FOSSIL {
            get {
                object obj = ResourceManager.GetObject("CLAW_FOSSIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CLAW_FOSSIL_1 {
            get {
                object obj = ResourceManager.GetObject("CLAW_FOSSIL_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CLAW_FOSSIL_2 {
            get {
                object obj = ResourceManager.GetObject("CLAW_FOSSIL_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CLAW_FOSSIL_3 {
            get {
                object obj = ResourceManager.GetObject("CLAW_FOSSIL_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DAMP_ROCK {
            get {
                object obj = ResourceManager.GetObject("DAMP_ROCK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dirt {
            get {
                object obj = ResourceManager.GetObject("dirt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DOME_FOSSIL {
            get {
                object obj = ResourceManager.GetObject("DOME_FOSSIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DRACO_PLATE {
            get {
                object obj = ResourceManager.GetObject("DRACO_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DREAD_PLATE {
            get {
                object obj = ResourceManager.GetObject("DREAD_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EARTH_PLATE {
            get {
                object obj = ResourceManager.GetObject("EARTH_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EVERSTONE {
            get {
                object obj = ResourceManager.GetObject("EVERSTONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FIRE_STONE {
            get {
                object obj = ResourceManager.GetObject("FIRE_STONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FIST_PLATE {
            get {
                object obj = ResourceManager.GetObject("FIST_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FLAME_PLATE {
            get {
                object obj = ResourceManager.GetObject("FLAME_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GREEN_SHARD {
            get {
                object obj = ResourceManager.GetObject("GREEN_SHARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HARD_STONE {
            get {
                object obj = ResourceManager.GetObject("HARD_STONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HEART_SCALE {
            get {
                object obj = ResourceManager.GetObject("HEART_SCALE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HEAT_ROCK {
            get {
                object obj = ResourceManager.GetObject("HEAT_ROCK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HELIX_FOSSIL {
            get {
                object obj = ResourceManager.GetObject("HELIX_FOSSIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HELIX_FOSSIL_1 {
            get {
                object obj = ResourceManager.GetObject("HELIX_FOSSIL_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICICLE_PLATE {
            get {
                object obj = ResourceManager.GetObject("ICICLE_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICY_ROCK {
            get {
                object obj = ResourceManager.GetObject("ICY_ROCK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap INSECT_PLATE {
            get {
                object obj = ResourceManager.GetObject("INSECT_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_BALL {
            get {
                object obj = ResourceManager.GetObject("IRON_BALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IRON_PLATE {
            get {
                object obj = ResourceManager.GetObject("IRON_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LARGE_BLUE_SPHERE {
            get {
                object obj = ResourceManager.GetObject("LARGE_BLUE_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LARGE_GREEN_SPHERE {
            get {
                object obj = ResourceManager.GetObject("LARGE_GREEN_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LARGE_PALE_SPHERE {
            get {
                object obj = ResourceManager.GetObject("LARGE_PALE_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LARGE_PRISM_SPHERE {
            get {
                object obj = ResourceManager.GetObject("LARGE_PRISM_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LARGE_RED_SPHERE {
            get {
                object obj = ResourceManager.GetObject("LARGE_RED_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LEAF_STONE {
            get {
                object obj = ResourceManager.GetObject("LEAF_STONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LEAF_STONE_1 {
            get {
                object obj = ResourceManager.GetObject("LEAF_STONE_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LIGHT_CLAY {
            get {
                object obj = ResourceManager.GetObject("LIGHT_CLAY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MAX_REVIVE {
            get {
                object obj = ResourceManager.GetObject("MAX_REVIVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MEADOW_PLATE {
            get {
                object obj = ResourceManager.GetObject("MEADOW_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MIND_PLATE {
            get {
                object obj = ResourceManager.GetObject("MIND_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MOON_STONE {
            get {
                object obj = ResourceManager.GetObject("MOON_STONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MOON_STONE_1 {
            get {
                object obj = ResourceManager.GetObject("MOON_STONE_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ODD_KEYSTONE {
            get {
                object obj = ResourceManager.GetObject("ODD_KEYSTONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OLD_AMBER {
            get {
                object obj = ResourceManager.GetObject("OLD_AMBER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OLD_AMBER_1 {
            get {
                object obj = ResourceManager.GetObject("OLD_AMBER_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OVAL_STONE {
            get {
                object obj = ResourceManager.GetObject("OVAL_STONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RARE_BONE {
            get {
                object obj = ResourceManager.GetObject("RARE_BONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RARE_BONE_1 {
            get {
                object obj = ResourceManager.GetObject("RARE_BONE_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RED_SHARD {
            get {
                object obj = ResourceManager.GetObject("RED_SHARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap REVIVE {
            get {
                object obj = ResourceManager.GetObject("REVIVE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock {
            get {
                object obj = ResourceManager.GetObject("rock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_A {
            get {
                object obj = ResourceManager.GetObject("rock_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_B {
            get {
                object obj = ResourceManager.GetObject("rock_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_C {
            get {
                object obj = ResourceManager.GetObject("rock_C", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_D {
            get {
                object obj = ResourceManager.GetObject("rock_D", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_E {
            get {
                object obj = ResourceManager.GetObject("rock_E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_F {
            get {
                object obj = ResourceManager.GetObject("rock_F", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_G {
            get {
                object obj = ResourceManager.GetObject("rock_G", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_H {
            get {
                object obj = ResourceManager.GetObject("rock_H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_I {
            get {
                object obj = ResourceManager.GetObject("rock_I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_J {
            get {
                object obj = ResourceManager.GetObject("rock_J", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_K {
            get {
                object obj = ResourceManager.GetObject("rock_K", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_L {
            get {
                object obj = ResourceManager.GetObject("rock_L", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_M {
            get {
                object obj = ResourceManager.GetObject("rock_M", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_N {
            get {
                object obj = ResourceManager.GetObject("rock_N", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_O {
            get {
                object obj = ResourceManager.GetObject("rock_O", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_P {
            get {
                object obj = ResourceManager.GetObject("rock_P", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_Q {
            get {
                object obj = ResourceManager.GetObject("rock_Q", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_R {
            get {
                object obj = ResourceManager.GetObject("rock_R", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_S {
            get {
                object obj = ResourceManager.GetObject("rock_S", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_T {
            get {
                object obj = ResourceManager.GetObject("rock_T", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_U {
            get {
                object obj = ResourceManager.GetObject("rock_U", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_V {
            get {
                object obj = ResourceManager.GetObject("rock_V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rock_W {
            get {
                object obj = ResourceManager.GetObject("rock_W", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ROOT_FOSSIL {
            get {
                object obj = ResourceManager.GetObject("ROOT_FOSSIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ROOT_FOSSIL_1 {
            get {
                object obj = ResourceManager.GetObject("ROOT_FOSSIL_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ROOT_FOSSIL_2 {
            get {
                object obj = ResourceManager.GetObject("ROOT_FOSSIL_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ROOT_FOSSIL_3 {
            get {
                object obj = ResourceManager.GetObject("ROOT_FOSSIL_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sand {
            get {
                object obj = ResourceManager.GetObject("sand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKULL_FOSSIL {
            get {
                object obj = ResourceManager.GetObject("SKULL_FOSSIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SKY_PLATE {
            get {
                object obj = ResourceManager.GetObject("SKY_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMALL_BLUE_SPHERE {
            get {
                object obj = ResourceManager.GetObject("SMALL_BLUE_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMALL_GREEN_SPHERE {
            get {
                object obj = ResourceManager.GetObject("SMALL_GREEN_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMALL_PALE_SPHERE {
            get {
                object obj = ResourceManager.GetObject("SMALL_PALE_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMALL_PRISM_SPHERE {
            get {
                object obj = ResourceManager.GetObject("SMALL_PRISM_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMALL_RED_SPHERE {
            get {
                object obj = ResourceManager.GetObject("SMALL_RED_SPHERE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SMOOTH_ROCK {
            get {
                object obj = ResourceManager.GetObject("SMOOTH_ROCK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPLASH_PLATE {
            get {
                object obj = ResourceManager.GetObject("SPLASH_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPOOKY_PLATE {
            get {
                object obj = ResourceManager.GetObject("SPOOKY_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STAR_PIECE {
            get {
                object obj = ResourceManager.GetObject("STAR_PIECE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap STONE_PLATE {
            get {
                object obj = ResourceManager.GetObject("STONE_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SUN_STONE {
            get {
                object obj = ResourceManager.GetObject("SUN_STONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THUNDER_STONE {
            get {
                object obj = ResourceManager.GetObject("THUNDER_STONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TOXIC_PLATE {
            get {
                object obj = ResourceManager.GetObject("TOXIC_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WATER_STONE {
            get {
                object obj = ResourceManager.GetObject("WATER_STONE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YELLOW_SHARD {
            get {
                object obj = ResourceManager.GetObject("YELLOW_SHARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZAP_PLATE {
            get {
                object obj = ResourceManager.GetObject("ZAP_PLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
